import { createContext, useContext, useEffect, useMemo, useState } from "react";

const translations = {
  en: {
    home: "Home",
    tracker: "Go-Tracker",
    progress: "Progress",
    rankings: "Rankings",
    profile: "Profile",
    loginTitle: "Welcome back",
    loginSubtitle: "Login with your username to continue your green journey.",
    registerTitle: "Create account",
    registerSubtitle: "Register first, then login and complete onboarding.",
    username: "Username",
    password: "Password",
    email: "Email",
    login: "Login",
    register: "Register",
    onboardingTitle: "Complete your profile",
    onboardingSubtitle: "This is required after first login before entering Carbon-Go.",
    fullName: "Full name",
    address: "Address",
    gender: "Gender",
    selectGender: "Select gender",
    female: "Female",
    male: "Male",
    phone: "Phone number",
    bio: "Bio (Optional)",
    finishOnboarding: "Finish onboarding",
    homeTitle: "Your daily choices shape the planet",
    homeSubtitle: "Track your environmental behavior, reduce carbon footprint, save water, and become part of a global green movement.",
    startNow: "Start Now",
    forestTitle: "Immerse in nature's resilience",
    forestDesc: "Real forests and scenery inspire environmental action. Every tree, stream, and meadow reminds us why tracking our footprint matters.",
    planetPulse: "Planet Pulse",
    didYouKnow: "Did you know? inspiring facts to fuel your eco-journey",
    trackerTitle: "Carbon Tracker · CU Activity Dashboard",
    cuTracker: "Carbon Unit (CU) Tracker",
    trackerTagline: "Track your daily environmental impact · Based on Relative Impact Assessment",
    school: "School",
    homeCategory: "Home",
    energy: "Energy",
    consumption: "Consumption",
    waste: "Waste",
    environment: "Environment",
    schoolTransportation: "School Transportation",
    homeActivity: "Home Activity",
    homeTransportation: "Home Transportation",
    energyActivity: "Energy Activity",
    consumptionActivity: "Consumption Activity",
    wasteActivity: "Waste Activity",
    environmentActivity: "Environment Activity",
    singleChoiceHint: "Please select ONLY ONE option for this category.",
    multiChoiceHint: "You may select more than one option for this category.",
    selected: "selected",
    otherSurvey: "Others: user input the activity not on the list",
    noCu: "No CU",
    back: "Back",
    next: "Next",
    submitSurvey: "Submit Survey",
    surveySelectOne: "Please select at least one activity before submitting.",
    surveySaved: "Survey log saved.",
    logNew: "Log New Activity",
    all: "All",
    other: "Other",
    manualActivity: "Manual activity name",
    noteOptional: "Note optional",
    noSelected: "No activity selected",
    logSelected: "Log Selected Activity",
    totalCu: "Total Carbon Units (CU)",
    neutral: "Neutral Impact",
    positive: "Positive Impact",
    negative: "Negative Impact",
    totalActivities: "Total Activities",
    goodActions: "Good Actions",
    badActions: "Bad Actions",
    ecoRatio: "Eco Ratio",
    activityLog: "Activity Log",
    noActivities: "No activities logged",
    guideTitle: "Carbon Unit (CU) Guide",
    guideButton: "Got it! Start Tracking",
    openGuide: "Open Carbon Unit guide",
    assessmentBasis: "Assessment Basis:",
    assessmentText: "Carbon Unit values are determined using Relative Impact Approach, considering each activity's carbon contribution and ease of behavior change for students.",
    researchNote: "Research Note:",
    researchText: "This system measures real student behavior, provides intervention through feedback, and tracks measurable behavior change (-5 to +5).",
    carbonScale: "Carbon Unit Scale",
    cuValue: "CU Value",
    impactCategory: "Impact Category",
    tip: "Tip:",
    guideTip: "This guide appears once before your first measurement session.",
    progressUnits: "Your Carbon Units (CU)",
    earned: "Earned from eco-actions in Go-Tracker",
    journey: "Journey completion",
    viewRankLog: "View Rank Log",
    rankJourney: "Your Rank Journey",
    achievedOn: "Achieved on",
    close: "Close",
    noRankChanges: "No rank changes yet.",
    startEcoJourney: "Start your eco-journey by earning Carbon Units!",
    toReachRank: "to reach",
    rankProgressHint: "Complete quests and earn Carbon Units to advance to the next rank!",
    guestRank: "Guest",
    explorerRank: "Explorer",
    guardianRank: "Guardian",
    heroRank: "Hero",
    maxLevel: "MAX LEVEL",
    rankClimbHint: "Complete +1 quest, +1 badge, and +1 milestone to climb.",
    nextRank: "Next rank",
    questActivityLogsCount: "Quest/activity logs",
    badgesEarnedCount: "Badges earned",
    milestonesCompletedCount: "Milestones completed",
    activityQuestLogs: "Activity / Quest Logs",
    milestones: "Achievements",
    milestoneBasis: "Based on Journey Points",
    badges: "Eco-Badges",
    badgeProof: "Based on Carbon Unit (CU)",
    activeQuests: "Active Quests",
    questHint: "Complete to earn Journey Points",
    reward: "Reward",
    requires: "Requires",
    youHave: "You have",
    completed: "Completed",
    need: "Need",
    unlocked: "Unlocked",
    earnedBadge: "Earned",
    journeyPoints: "Journey Points",
    carbonUnit: "Carbon Unit (CU)",
    progressFootnote: "Your carbon journey is dynamic — track actions, earn Journey Points, unlock badges, and climb the ranks!",
    noBadges: "No badges earned yet.",
    rankTitle: "EcoChampions",
    rankSubtitle: "Leaderboard based on total Carbon Units",
    rank: "Rank",
    user: "User",
    profileTitle: "My Eco Profile",
    edit: "Edit",
    score: "My Carbon Score",
    logout: "Log Out"
  },
  id: {
    home: "Beranda",
    tracker: "Pengukur",
    progress: "Kemajuan",
    rankings: "Peringkat",
    profile: "Profil",
    loginTitle: "Selamat datang kembali",
    loginSubtitle: "Login dengan username untuk melanjutkan perjalanan hijaumu.",
    registerTitle: "Buat akun",
    registerSubtitle: "Daftar dulu, lalu login dan lengkapi onboarding.",
    username: "Username",
    password: "Password",
    email: "Email",
    login: "Masuk",
    register: "Daftar",
    onboardingTitle: "Lengkapi profilmu",
    onboardingSubtitle: "Wajib diisi setelah login pertama sebelum masuk Carbon-Go.",
    fullName: "Nama asli",
    address: "Alamat",
    gender: "Gender",
    selectGender: "Pilih gender",
    female: "Perempuan",
    male: "Laki-laki",
    phone: "No telp",
    bio: "Bio (Opsional)",
    finishOnboarding: "Selesaikan onboarding",
    homeTitle: "Pilihan harimu membentuk planet",
    homeSubtitle: "Lacak perilaku lingkunganmu, kurangi jejak karbon, hemat air, dan jadilah bagian dari gerakan hijau global.",
    startNow: "Mulai Sekarang",
    forestTitle: "Benamkan diri dalam ketahanan alam",
    forestDesc: "Hutan dan pemandangan nyata menginspirasi aksi lingkungan. Setiap pohon, sungai, dan padang rumput mengingatkan kita mengapa melacak jejak itu penting.",
    planetPulse: "Denyut Planet",
    didYouKnow: "Tahukah kamu? fakta inspiratif untuk perjalanan eko-mu",
    trackerTitle: "Pelacak Karbon · Dasbor Aktivitas CU",
    cuTracker: "Pelacak Carbon Unit (CU)",
    trackerTagline: "Lacak dampak lingkungan harianmu · Berdasarkan Relative Impact Assessment",
    school: "Sekolah",
    homeCategory: "Rumah",
    energy: "Energi",
    consumption: "Konsumsi",
    waste: "Sampah",
    environment: "Lingkungan",
    schoolTransportation: "Transportasi Sekolah",
    homeActivity: "Aktivitas Rumah",
    homeTransportation: "Transportasi Rumah",
    energyActivity: "Aktivitas Energi",
    consumptionActivity: "Aktivitas Konsumsi",
    wasteActivity: "Aktivitas Sampah",
    environmentActivity: "Aktivitas Lingkungan",
    singleChoiceHint: "Pilih HANYA SATU opsi untuk kategori ini.",
    multiChoiceHint: "Kamu boleh memilih lebih dari satu opsi untuk kategori ini.",
    selected: "dipilih",
    otherSurvey: "Lainnya: input aktivitas yang tidak ada di daftar",
    noCu: "Tanpa CU",
    back: "Kembali",
    next: "Lanjut",
    submitSurvey: "Kirim Survey",
    surveySelectOne: "Pilih minimal satu aktivitas sebelum mengirim.",
    surveySaved: "Survey log berhasil disimpan.",
    logNew: "Catat Aktivitas Baru",
    all: "Semua",
    other: "Lainnya",
    manualActivity: "Nama aktivitas manual",
    noteOptional: "Catatan optional",
    noSelected: "Tidak ada aktivitas dipilih",
    logSelected: "Catat Aktivitas Terpilih",
    totalCu: "Total Unit Karbon (CU)",
    neutral: "Dampak Netral",
    positive: "Dampak Positif",
    negative: "Dampak Negatif",
    totalActivities: "Total Aktivitas",
    goodActions: "Aksi Baik",
    badActions: "Aksi Buruk",
    ecoRatio: "Rasio Eko",
    activityLog: "Catatan Aktivitas",
    noActivities: "Belum ada aktivitas tercatat",
    guideTitle: "Panduan Unit Karbon (CU)",
    guideButton: "Mengerti! Mulai Lacak",
    openGuide: "Buka panduan Unit Karbon",
    assessmentBasis: "Dasar Penilaian:",
    assessmentText: "Nilai Unit Karbon ditentukan dengan Relative Impact Approach, mempertimbangkan kontribusi karbon setiap aktivitas dan kemudahan perubahan perilaku untuk siswa.",
    researchNote: "Catatan Riset:",
    researchText: "Sistem ini mengukur perilaku nyata siswa, memberi intervensi melalui feedback, dan melacak perubahan perilaku terukur (-5 sampai +5).",
    carbonScale: "Skala Unit Karbon",
    cuValue: "Nilai CU",
    impactCategory: "Kategori Dampak",
    tip: "Tip:",
    guideTip: "Panduan ini muncul satu kali sebelum sesi pengukuran pertamamu.",
    progressUnits: "Unit Karbonmu (CU)",
    earned: "Diperoleh dari aksi eko di Go-Tracker",
    journey: "Penyelesaian Perjalanan",
    viewRankLog: "Lihat Catatan Peringkat",
    rankJourney: "Perjalanan Peringkatmu",
    achievedOn: "Dicapai pada",
    close: "Tutup",
    noRankChanges: "Belum ada perubahan peringkat.",
    startEcoJourney: "Mulai perjalanan eko-mu dengan mengumpulkan Unit Karbon!",
    toReachRank: "untuk mencapai",
    rankProgressHint: "Selesaikan misi dan kumpulkan Unit Karbon untuk naik ke peringkat berikutnya!",
    guestRank: "Tamu",
    explorerRank: "Penjelajah",
    guardianRank: "Penjaga",
    heroRank: "Pahlawan",
    maxLevel: "LEVEL MAKSIMAL",
    rankClimbHint: "Selesaikan +1 misi, +1 lencana, dan +1 pencapaian untuk naik peringkat.",
    nextRank: "Peringkat berikutnya",
    questActivityLogsCount: "Catatan misi/aktivitas",
    badgesEarnedCount: "Lencana didapat",
    milestonesCompletedCount: "Pencapaian selesai",
    activityQuestLogs: "Catatan Aktivitas / Misi",
    milestones: "Pencapaian",
    milestoneBasis: "Berdasarkan Poin Perjalanan",
    badges: "Lencana Eko",
    badgeProof: "Berdasarkan Carbon Unit (CU)",
    activeQuests: "Misi Aktif",
    questHint: "Selesaikan untuk mendapat Poin Perjalanan",
    reward: "Hadiah",
    requires: "Syarat",
    youHave: "Kamu punya",
    completed: "Selesai",
    need: "Butuh",
    unlocked: "Terbuka",
    earnedBadge: "Didapat",
    journeyPoints: "Poin Perjalanan",
    carbonUnit: "Carbon Unit (CU)",
    progressFootnote: "Perjalanan karbonmu dinamis — catat aksi, kumpulkan Poin Perjalanan, buka badge, dan naik peringkat!",
    noBadges: "Belum ada badge didapat.",
    rankTitle: "EcoChampions",
    rankSubtitle: "Leaderboard berdasarkan total Unit Karbon",
    rank: "Peringkat",
    user: "User",
    profileTitle: "Profil Eko Saya",
    edit: "Edit",
    score: "Skor Karbon Saya",
    logout: "Keluar"
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => localStorage.getItem("carbon_language") || "id");

  useEffect(() => {
    localStorage.setItem("carbon_language", language);
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t(key) {
      return translations[language]?.[key] || translations.en[key] || key;
    }
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}
